### ISSUE TITLE
[Bug] Compiling Rope leads to illegal memory access

### ISSUE THREAD

**Issue by conceptofmind** [fla-org/flash-linear-attention#180]
### Checklist

- [x] I have checked [FAQs](https://github.com/fla-org/flash-linear-attention/blob/main/FAQs.md) and existing issues for similar problems
- [x] Please report this bug in English to ensure wider understanding and support

### Describe the Bug

Hello,

Thank you for your amazing work. Currently, when trying to compile a new model with the flash linear rope I am running into the error:
```
torch._dynamo.exc.InternalTorchDynamoError: RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
Thank you for the help.

Enrico

### Steps to Reproduce the Bug

Given the Attention Mechanism below the model should compile:
```python
from fla.modules import RotaryEmbedding

class Attention(nn.Module):
    def __init__(
        self,
        dim: int,
        heads: int,
        dropout: float,
        use_qkv_bias: bool,
        use_bias: bool,
        scale: float = None,
    ):
        super().__init__()

        head_dim = int(dim // heads)
        inner_dim = int(head_dim * heads) 
        
        self.heads = heads
        self.head_dim = head_dim

        assert int(dim // heads) <= 256 and int(dim // heads) >= 64, "dim // heads must be between 64 and 256."
        assert inner_dim % heads == 0, "num_heads must divide dim."

        self.to_qkv = nn.Linear(dim, inner_dim * 3, bias=use_qkv_bias)
        self.to_out = nn.Linear(inner_dim, dim, bias=use_bias)

        self.rotary_emb = RotaryEmbedding(dim)

        self.dropout = dropout
        self.scale = scale

    def forward(self, x, attn_mask=None):
        """
        b: batch size
        n: sequence length
        h: number of heads
        head_dim: dim // heads
        """
        b, n, h = x.shape[0], x.shape[1], self.heads

        """
        In Shape: (b, n, dim)
        Out Shape: (b, n, dim)
        """
        q, k, v = self.to_qkv(x).chunk(3, dim = -1)

        """
        In Shape: (b, n, dim)
        Q K V View: (b, n, dim) -> (b, n, h, head_dim)
        V Transpose: (b, n, h, head_dim) -> (b, h, n, head_dim)
        Q K Out Shape: (b, n, h, head_dim)
        V Out Shape: (b, h, n, head_dim)
        """
        q = q.view(b, n, h, self.head_dim)
        k = k.view(b, n, h, self.head_dim).
        v = v.view(b, n, h, self.head_dim).transpose(1, 2)

        """
        In Shape: (b, h, n, head_dim)
        """
        q, k = self.rotary_emb(q, k)

        q = q.transpose(1, 2)
        k = k.transpose(1, 2)

        """
        In Shape: (b, h, n, head_dim)
        Out Shape: (b, h, n, head_dim)
        """
        out = F.scaled_dot_product_attention(
            q, k, v, 
            attn_mask=attn_mask, 
            is_causal=False, 
            dropout_p=self.dropout,
            scale=self.scale,
        )

        """
        In Shape: (b, h, n, head_dim)
        Transpose: (b, h, n, head_dim) -> (b, n, h, head_dim)
        Reshape: (b, n, h, head_dim) -> (b, n, head_dim * h)
        Out Shape: (b, n, head_dim * h)
        """
        out = out.transpose(1, 2).contiguous().reshape(b, n, self.head_dim * h)
        out = self.to_out(out)

        return out
```

### Expected Behavior

The model should compile.

Also, for this rope implementation is N `batch_size` and T `seq_len`? I will likely need to adjust those dims if so.

### Environment Information

1. Torch: 2.6.0+cu126
2. Triton: 3.2.0

**Comment by yzhangcs** [comment]
@conceptofmind Hello, could you provide reproducible scripts. I didn't met issues by passing inputs into the class you defined

**Comment by conceptofmind** [comment]
> [@conceptofmind](https://github.com/conceptofmind) Hello, could you provide reproducible scripts. I didn't met issues by passing inputs into the class you defined

Hi @yzhangcs,

Thank you for the response.

Here is a basic script for the architecture:
```python
import torch
import torch.nn as nn
import torch.nn.functional as F
import functools
from models.rope import RotaryEmbedding
from models.norm import RMSNorm


@torch.jit.script
def sqrelu_fwd(x):
    r = F.relu(x)
    return (r * r).to(dtype=x.dtype)

@torch.jit.script
def sqrelu_bwd(g, x):
    return (2.0 * g * F.relu(x)).to(dtype=x.dtype)

class SQ_ReLU_Function(torch.autograd.Function):
    @staticmethod
    def forward(ctx, input):
        ctx.save_for_backward(input)
        return sqrelu_fwd(input)

    @staticmethod
    def backward(ctx, grad_output):
        (input,) = ctx.saved_tensors
        tmp = sqrelu_bwd(grad_output, input)
        return tmp

sq_relu_impl = SQ_ReLU_Function.apply

# MLP
class MLP(nn.Module):
    def __init__(
        self, 
        dim: int, 
        hidden_dim: int, 
        dropout: float,
        use_bias: bool,
    ):
        super().__init__()

        self.linear_in = nn.Linear(dim, hidden_dim, bias=use_bias)

        self.act_fn = sq_relu_impl
        
        self.d1 = nn.Dropout(dropout)
        
        self.linear_out = nn.Linear(hidden_dim, dim, bias=use_bias)
        
        self.d2 = nn.Dropout(dropout)

    def forward(self, x):
        x = self.linear_in(x)
        x = self.act_fn(x)
        x = self.d1(x)
        x = self.linear_out(x)
        x = self.d2(x)
        return x

# Attention
class Attention(nn.Module):
    def __init__(
        self,
        dim: int,
        heads: int,
        dropout: float,
        use_qkv_bias: bool,
        use_bias: bool,
        scale: float = None,
    ):
        super().__init__()

        head_dim = int(dim // heads)
        inner_dim = int(head_dim * heads) 
        
        self.heads = heads
        self.head_dim = head_dim

        assert int(dim // heads) <= 256 and int(dim // heads) >= 64, "dim // heads must be between 64 and 256."
        assert inner_dim % heads == 0, "num_heads must divide dim."

        self.to_qkv = nn.Linear(dim, inner_dim * 3, bias=use_qkv_bias)
        self.to_out = nn.Linear(inner_dim, dim, bias=use_bias)

        self.rotary_emb = RotaryEmbedding(dim)

        self.dropout = dropout
        self.scale = scale

    def forward(self, x):
        """
        b: batch size
        n: sequence length
        h: number of heads
        head_dim: dim // heads
        """
        b, n, h = x.shape[0], x.shape[1], self.heads

        """
        In Shape: (b, n, dim)
        Out Shape: (b, n, dim)
        """
        q, k, v = self.to_qkv(x).chunk(3, dim = -1)

        """
        In Shape: (b, n, dim)
        View: (b, n, dim) -> (b, n, h, head_dim)
        Transpose: (b, n, h, head_dim) -> (b, h, n, head_dim)
        Out Shape: (b, h, n, head_dim)
        """
        q = q.view(b, n, h, self.head_dim)
        k = k.view(b, n, h, self.head_dim)
        v = v.view(b, n, h, self.head_dim).transpose(1, 2)

        """
        In Shape: (b, h, n, head_dim)
        """
        q, k = self.rotary_emb(q, k)
        q = q.transpose(1, 2)
        k = k.transpose(1, 2)

        """
        In Shape: (b, h, n, head_dim)
        Out Shape: (b, h, n, head_dim)
        """
        out = F.scaled_dot_product_attention(
            q, k, v, 
            attn_mask=None, 
            is_causal=False, 
            dropout_p=self.dropout,
            scale=self.scale,
        )

        """
        In Shape: (b, h, n, head_dim)
        Transpose: (b, h, n, head_dim) -> (b, n, h, head_dim)
        Reshape: (b, n, h, head_dim) -> (b, n, head_dim * h)
        Out Shape: (b, n, head_dim * h)
        """
        out = out.transpose(1, 2).contiguous().reshape(b, n, self.head_dim * h)
        out = self.to_out(out)

        return out

# TransformerBlock
class TransformerBlock(nn.Module):
    def __init__(
        self,
        dim: int,
        heads: int,
        dropout: float,
        use_qkv_bias: bool,
        use_bias: bool,
    ):
        super().__init__()

        ff_dim = int(dim * 4)

        self.attn_norm = RMSNorm(dim)
        self.attn = Attention(
            dim, 
            heads, 
            dropout,
            use_qkv_bias,
            use_bias,
        )
        self.mlp_norm = RMSNorm(dim)
        self.mlp = MLP(
            dim, 
            ff_dim, 
            dropout, 
            use_bias
        )

    def forward(self, x):
        x = x + self.attn(self.attn_norm(x))
        x = x + self.mlp(self.mlp_norm(x))
        return x

# Transformer
class Transformer(nn.Module):
    def __init__(
        self,
        dim: int,
        depth: int,
        heads: int,
        dropout: float,
        use_qkv_bias: bool,
        use_bias: bool,
    ):
        super().__init__()

        self.layers = nn.ModuleList([])
        for _ in range(depth):
            self.layers.append(
                TransformerBlock(dim, heads, dropout, use_qkv_bias, use_bias)
            )

    def forward(self, x):
        for block in self.layers:
            x = block(x)
        return x

# LMHead
class LMHead(nn.Module):
    def __init__(
        self,
        dim: int,
        num_tokens: int,
        use_bias: bool,
    ):
        super().__init__()

        self.lmhead_norm = RMSNorm(dim)
        self.to_logits = nn.Linear(dim, num_tokens, bias=use_bias)

    def forward(self, x):
        x = self.lmhead_norm(x)
        x = self.to_logits(x)
        return x

# Encoder
class Encoder(nn.Module):
    def __init__(
        self,
        num_tokens: int,
        dim: int,
        depth: int,
        heads: int,
        dropout: float = 0.0,
        use_qkv_bias: bool = True,
        use_bias: bool = True,
        padding_idx: int = 0,
    ):
        super().__init__()

        self.embed = nn.Embedding(num_tokens, dim, padding_idx,)
        self.transformer = Transformer(
            dim, 
            depth, 
            heads,
            dropout,
            use_qkv_bias,
            use_bias,
        )
        self.lmhead = LMHead(dim, num_tokens, use_bias,)

        self.lmhead.to_logits.weight = self.embed.weight
        nn.init.normal_(self.embed.weight, std=0.02)

    def forward(self, x):
        x = self.embed(x)
        x = self.transformer(x)
        x = self.lmhead(x)
        return x

if __name__ == "__main__":

    torch.set_float32_matmul_precision('high')

    # Test Encoder
    x = torch.randint(0, 32000, (1, 2048)).cuda()

    model = Encoder(
        num_tokens=32000, 
        dim=2048,
        depth=6,
        heads=8,
    ).cuda()

    model = torch.compile(model)

    out = model(x)

    print(out[0])

    n_params_torch = sum(
        p.numel() for p in model.parameters() if p.requires_grad
    )

    print(f"Number of parameters in torch model: {n_params_torch}")
```

When I use a different RoPE kernel such as the one from Liger it compiles smoothly. I am unsure as to why.

I appreciate all of your help.

Thank you,

Enrico

**Comment by yzhangcs** [comment]
@conceptofmind That still works for me:
```py
tensor([[-0.4309, -0.1244,  0.2107,  ..., -0.3310,  0.0867,  0.7308],
        [ 0.6221, -1.2253,  0.1032,  ...,  0.5258,  1.2898, -0.6518],
        [ 0.8487, -1.4415,  0.1452,  ...,  0.7175,  0.7691,  0.1737],
        ...,
        [ 1.1741, -1.9268, -0.0137,  ...,  1.0673,  0.8184, -0.1385],
        [ 0.5562, -1.4768,  0.2386,  ...,  0.2397,  0.6000, -0.2193],
        [ 0.9439, -1.3372,  0.0420,  ...,  0.4284,  1.1916, -0.4148]],
       device='cuda:0', grad_fn=<SelectBackward0>)
Number of parameters in torch model: 367695104
```
Could you locate the errors more precisely by adding `CUDA_LAUNCH_BLOCKING=1`

**Comment by conceptofmind** [comment]
> [@conceptofmind](https://github.com/conceptofmind) That still works for me:
> 
> tensor([[-0.4309, -0.1244,  0.2107,  ..., -0.3310,  0.0867,  0.7308],
>         [ 0.6221, -1.2253,  0.1032,  ...,  0.5258,  1.2898, -0.6518],
>         [ 0.8487, -1.4415,  0.1452,  ...,  0.7175,  0.7691,  0.1737],
>         ...,
>         [ 1.1741, -1.9268, -0.0137,  ...,  1.0673,  0.8184, -0.1385],
>         [ 0.5562, -1.4768,  0.2386,  ...,  0.2397,  0.6000, -0.2193],
>         [ 0.9439, -1.3372,  0.0420,  ...,  0.4284,  1.1916, -0.4148]],
>        device='cuda:0', grad_fn=<SelectBackward0>)
> Number of parameters in torch model: 367695104
> Could you locate the errors more precisely by adding `CUDA_LAUNCH_BLOCKING=1`

Haha interesting.

I will run now with `CUDA_LAUNCH_BLOCKING=1` and report.

**Comment by conceptofmind** [comment]
> [@conceptofmind](https://github.com/conceptofmind) That still works for me:
> 
> tensor([[-0.4309, -0.1244,  0.2107,  ..., -0.3310,  0.0867,  0.7308],
>         [ 0.6221, -1.2253,  0.1032,  ...,  0.5258,  1.2898, -0.6518],
>         [ 0.8487, -1.4415,  0.1452,  ...,  0.7175,  0.7691,  0.1737],
>         ...,
>         [ 1.1741, -1.9268, -0.0137,  ...,  1.0673,  0.8184, -0.1385],
>         [ 0.5562, -1.4768,  0.2386,  ...,  0.2397,  0.6000, -0.2193],
>         [ 0.9439, -1.3372,  0.0420,  ...,  0.4284,  1.1916, -0.4148]],
>        device='cuda:0', grad_fn=<SelectBackward0>)
> Number of parameters in torch model: 367695104
> Could you locate the errors more precisely by adding `CUDA_LAUNCH_BLOCKING=1`

Here is the output with `CUDA_LAUNCH_BLOCKING=1`:

```
Traceback (most recent call last):
  File "model.py", line 396, in <module>
    out = model(x)
  File "/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 574, in _fn
    return fn(*args, **kwargs)
  File "/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "model.py", line 374, in forward
    x = self.transformer(x)
  File "/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "model.py", line 313, in forward
    x = block(x)
  File "/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "model.py", line 286, in forward
    def forward(self, x):
  File "/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 745, in _fn
    return fn(*args, **kwargs)
  File "/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1184, in forward
    return compiled_fn(full_args)
  File "lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 310, in runtime_wrapper
    all_outs = call_func_at_runtime_with_args(
  File "/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/utils.py", line 126, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
  File "/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/utils.py", line 100, in g
    return f(*args)
  File "/lib/python3.10/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 1585, in forward
    fw_outs = call_func_at_runtime_with_args(
  File "/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/utils.py", line 126, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
  File "/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 490, in wrapper
    return compiled_fn(runtime_args)
  File "/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 672, in inner_fn
    outs = compiled_fn(args)
  File "/lib/python3.10/site-packages/torch/_inductor/output_code.py", line 466, in __call__
    return self.current_callable(inputs)
  File "/lib/python3.10/site-packages/torch/_inductor/utils.py", line 2128, in run
    return model(new_inputs)
  File "/tmp/torchinductor_/4f/c4fpgww3odnu4bydvvwb35pizv5kgvh5ho3akrbw26sbp5a5uxwn.py", line 445, in call
    rotary_embedding_kernel_1.run(buf8, buf5, buf6, buf7, 0, 1, 2048, 8, 256, 1024, 2048, 2048, False, False, False, False, grid=grid_wrapper_for_rotary_embedding_kernel_1, stream=stream0)
  File "/lib/python3.10/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 1079, in run
    return launcher(
  File "<string>", line 13, in launcher
  File "/lib/python3.10/site-packages/triton/backends/nvidia/driver.py", line 444, in __call__
    self.launch(*args, **kwargs)
RuntimeError: Triton Error [CUDA]: an illegal memory access was encountered
```

**Comment by yzhangcs** [comment]
@conceptofmind https://github.com/fla-org/flash-linear-attention/blob/main/fla/layers/attn.py#L70

You should pass `head_dim` when creating `RotaryEmbedding`

**Comment by conceptofmind** [comment]
> [@conceptofmind](https://github.com/conceptofmind) You should pass `head_dim` when creating `RotaryEmbedding`
> 
> [flash-linear-attention/fla/layers/attn.py](https://github.com/fla-org/flash-linear-attention/blob/965c355397641a0b75f2edd36789aa2f83e9961a/fla/layers/attn.py#L70)
> 
> Line 70 in [965c355](/fla-org/flash-linear-attention/commit/965c355397641a0b75f2edd36789aa2f83e9961a)
> 
>  self.rotary = RotaryEmbedding(dim=self.head_dim, base=self.rope_theta)

Oh that solved it. Differences in RoPE implementations. Thank you!

Just to confirm also for this rope implementation it is `N` -> batch_size and `T` -> seq_len?

**Comment by yzhangcs** [comment]
@conceptofmind For `T`, yes
What do you mean by `N`?
The `N` here
https://github.com/fla-org/flash-linear-attention/blob/965c355397641a0b75f2edd36789aa2f83e9961a/fla/modules/rotary.py#L166

refers to the actual number of sequences, for normal training, i.e., non-varlen, this is exactly the same as batch_size, but for varlen training, the batch_size is 1, while `N` can be varied according how many sequence are packed.

**Comment by conceptofmind** [comment]
> [@conceptofmind](https://github.com/conceptofmind) For `T`, yes What do you mean by `N`?
> 
> [flash-linear-attention/fla/modules/rotary.py](https://github.com/fla-org/flash-linear-attention/blob/965c355397641a0b75f2edd36789aa2f83e9961a/fla/modules/rotary.py#L166)
> 
> Line 166 in [965c355](/fla-org/flash-linear-attention/commit/965c355397641a0b75f2edd36789aa2f83e9961a)
> 
>  N, T = cu_seqlens.shape[0] - 1, max_seqlen 
> The `N` here refers to the actual number of sequences, for normal training, i.e., non-varlen, this is exactly the same as batch_size, but for varlen training, the batch_size is 1, while `N` can be varied according to how many sequence are packed.

Thank you for the additional input.

I was referencing this line here: https://github.com/fla-org/flash-linear-attention/blob/965c355397641a0b75f2edd36789aa2f83e9961a/fla/modules/rotary.py#L290

**Comment by conceptofmind** [comment]
> [@conceptofmind](https://github.com/conceptofmind) oh, sorry, wrongly documented, should be `B`, i.e., batch_size.

No need to apologize haha. I greatly appreciate your help!

Ok, so it should be `(b, n, h, head_dim)` correctly matches `x: [B, T, H, D]`.

**Comment by yzhangcs** [comment]
Yes, exactly.
